### ISSUE TITLE
Saving a niml.dset using h5save fails due to unrecognized dtypes(?)

### ISSUE THREAD

**Issue by swaroopgj** [PyMVPA/PyMVPA#335]
I loaded a surface dataset from a .niml.dset file and niml.from_any() and it loads fine. But when I try to save the dataset using `h5save`, it spits out an error due to dtype of certain `sa` and  `a`. It looks like an issue with not handling unicode types, but I am not sure. Problematic dtypes look like '<U7' '<U4' when printing the ds. For now, I remove the attributes or convert them to strings before saving with h5save. @nno @yarikoptic

**Comment by nno** [comment]
I reproduced the problem. Using a NIML surface dataset with the following content:

    Dataset(array([[ 127.,  100.,  102., ...,  118.,  131.,  124.]], dtype=float32), sa=SampleAttributesCollection(items=[ArrayCollectable(name='labels', doc=None, value=array([u'#0'], 
      dtype='<U2'), length=1), ArrayCollectable(name='stats', doc=None, value=array([u'none'], 
      dtype='<U4'), length=1)]), fa=FeatureAttributesCollection(items=[]), a=DatasetAttributesCollection(items=[Collectable(name='history', doc=None, value=u'[nick@nicks-MacBook-Pro-2.local: Wed Jun 24 15:09:26 2015] 3dVol2Surf -spec mh_ico32_al.spec -surf_A smoothwm -sv s88_SurfVol_al2exp+orig -grid_parent s88_SurfVol_al2exp+orig -map_func mask -out_niml data.niml.dset -outcols_results')]))

I get the following error when using ``h5save``:

       Traceback (most recent call last):
      File "load.py", line 5, in <module>
        h5save('foo.h5py',data)
      File "/Users/nick/git/PyMVPA/mvpa2/base/hdf5.py", line 827, in h5save
        obj2hdf(hdf, data, name, **kwargs)
      File "/Users/nick/git/PyMVPA/mvpa2/base/hdf5.py", line 778, in obj2hdf
        _seqitems_to_hdf(pieces[1], args, memo, **kwargs)
      File "/Users/nick/git/PyMVPA/mvpa2/base/hdf5.py", line 525, in _seqitems_to_hdf
        obj2hdf(items, item, name=str(i), memo=memo, noid=noid, **kwargs)
      File "/Users/nick/git/PyMVPA/mvpa2/base/hdf5.py", line 764, in obj2hdf
        noid=True, **kwargs)
      File "/Users/nick/git/PyMVPA/mvpa2/base/hdf5.py", line 525, in _seqitems_to_hdf
        obj2hdf(items, item, name=str(i), memo=memo, noid=noid, **kwargs)
      File "/Users/nick/git/PyMVPA/mvpa2/base/hdf5.py", line 758, in obj2hdf
        _seqitems_to_hdf(obj, grp, memo, **kwargs)
      File "/Users/nick/git/PyMVPA/mvpa2/base/hdf5.py", line 525, in _seqitems_to_hdf
        obj2hdf(items, item, name=str(i), memo=memo, noid=noid, **kwargs)
      File "/Users/nick/git/PyMVPA/mvpa2/base/hdf5.py", line 778, in obj2hdf
        _seqitems_to_hdf(pieces[1], args, memo, **kwargs)
      File "/Users/nick/git/PyMVPA/mvpa2/base/hdf5.py", line 525, in _seqitems_to_hdf
        obj2hdf(items, item, name=str(i), memo=memo, noid=noid, **kwargs)
      File "/Users/nick/git/PyMVPA/mvpa2/base/hdf5.py", line 627, in obj2hdf
        hdf.create_dataset(name, None, None, obj, **kwargs)
      File "/Library/Python/2.7/site-packages/h5py/_hl/group.py", line 94, in create_dataset
        dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
      File "/Library/Python/2.7/site-packages/h5py/_hl/dataset.py", line 79, in make_new_dset
        tid = h5t.py_create(dtype, logical=1)
      File "h5t.pyx", line 1389, in h5py.h5t.py_create (h5py/h5t.c:13981)
      File "h5t.pyx", line 1469, in h5py.h5t.py_create (h5py/h5t.c:13873)
    TypeError: No conversion path for dtype: dtype('<U2')

which indeed seems to be of type Unicode (http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html)

@yoh, should the h5py module be able to support Unicode, or would it be better if the NIML code would use 'plain' strings?

**Comment by nno** [comment]
@yarikoptic not sure if you saw this issue because initially I didn't mention you in the comment.

**Comment by yarikoptic** [comment]
sorry -- missed it... h5py claims to support unicode strings (but not sure about numpy.ndarrays with unicode) but not numpy's : 
http://docs.h5py.org/en/latest/strings.html#what-about-numpy-s-u-type
"
What about NumPy’s U type?

NumPy also has a Unicode type, a UTF-32 fixed-width format (4-byte characters). HDF5 has no support for wide characters. Rather than trying to hack around this and “pretend” to support it, h5py will raise an error when attempting to create datasets or attributes of this type.
"

so -- boomer!... we would need to hack up the workaround at the level of h5save/load to convert to another dtype and bring it back

**Comment by nno** [comment]
@yarikoptic thanks for doing the research. It it worthwhile to spend much effort in chaining h5{save,load}? 

If the only reasonable use case is NIML datasets, then an alternative solution is just ensure that datasets based on from NIML (.niml.dset) files only have 'plain strings' (type 'str;), and not unicode strings. We're only talking about sample (.sa) and dataset (.a) elements here, nothing more complicated, so that should be straightforward to implement.

My understanding from the NIML standard [1] is that Unicode is not supported anyway, so there would be  no risk of losing information. 

[1] http://afni.nimh.nih.gov/afni/doc/misc/NIML_documentation/NIML_manual

**Comment by yarikoptic** [comment]
well... in python3 all strings are unicode, so we would see more and more of this case I guess.  Anyways -- hacked up some another level of obnoxification for our hdf5.py (#339).  Would be nice if you could try it on your specific use-case
