### ISSUE TITLE
Wrong order of operations in rfe examples

### ISSUE THREAD

**Issue by zingbretsen** [PyMVPA/PyMVPA#459]
Currently, your demo code norms across features, then takes the mean (or max), and then takes the absolute value.
```
# take sensitivities per each split, L2 norm, mean, abs them              
postproc=ChainMapper([ FxMapper('features', l2_normed),               
    FxMapper('samples', np.mean),                       
    FxMapper('samples', np.abs)])),   
```                   
http://www.pymvpa.org/generated/mvpa2.featsel.rfe.RFE.html
http://www.pymvpa.org/generated/mvpa2.featsel.rfe.SplitRFE.html

But shouldn't you norm, then take the absolute value, then take the mean? 

At least in linear SVM (which the examples use), both the positive and negative sensitivities are meaningful.

**Comment by yarikoptic** [comment]
your logic beats some gut feeling we (me? ;) ) had while crafting this example.  On few brief examples, it pretty much didn't make much of a difference -- some times one method beat the other, some times the other way around.  Another possible one could even be the max(abs(normed())) but that one lost to the other two ;)  But since meaning abs of normed values indeed makes more sense imho as well, I will reorder in this example and in the test. thanks again
