### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by johnmarktaylor91** [PyMVPA/PyMVPA#590]
I tried to install pymvpa with the following command:

python setup.py build_ext

However, I got the following error:
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/16569815/44670410-9dd49500-a9f0-11e8-84ea-c6fe63fd755a.png">

Any idea what might be going on?

**Comment by yarikoptic** [comment]
you seems to be using conda, so why not just `conda install -c conda-forge pymvpa2`?
https://anaconda.org/conda-forge/pymvpa2

**Comment by johnmarktaylor91** [comment]
I tried that, and get a long list of clashing dependencies (I'm using Python 3.6):

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/16569815/45716406-cb7eab00-bb64-11e8-837a-61f116d9119c.png">

**Comment by yarikoptic** [comment]
ah... didn't spot in the original report -- I am sad to report that python3 is not yet fully supported :-(.
Even though you should be able to build etc, some PyMVPA functionality is known to not pass our unitttests when under python3 so I would strongly advise against trying ATM.  We really need to find time and provide a proper conversion. We had multiple attempts and already contributed some piece meal steps to provide proper python 2+3 support from the same codebase (ATM using old 2to3) but not there yet.  That is why if I try to install it under conda with python 3.6 it tells me
```
The following packages will be DOWNGRADED:

    python:                        3.6.6-h5001a0f_0      conda-forge --> 2.7.15-h9fef7bc_0 conda-forge
```
but otherwise seems to not report any conflicts.  What is your underlying OS?

**Comment by johnmarktaylor91** [comment]
The OS is:

<img width="319" alt="image" src="https://user-images.githubusercontent.com/16569815/45718496-303d0400-bb6b-11e8-9866-99499040d3fd.png">

**Comment by yarikoptic** [comment]
so, if feasible, please install anaconda with python2, and just `conda install pymvpa2` there. Work is ongoing for python3 support (#525).
