### ISSUE TITLE
Error when using 'pjoin' module

### ISSUE THREAD

**Issue by rickwith** [PyMVPA/PyMVPA#616]
Can not using "pjoin" module with error message as "'NoneType' object has no attribute 'endswith', after checking script i found a 'Nonetype' return by 'cfg.get('location', 'tutorial data')'. 

Python version: 2.7.16
Pymvpa version: 2.6.5   

Thanks.

**Comment by yarikoptic** [comment]
so there is no configuration variable set to point to tutorial data. Just either specify it explicitly instead of using `cfg.get('location', 'tutorial data')` or first set `MVPA_LOCATION_TUTORIAL_DATA` environment variable to point to it.

Cheers,

PS pjoin is an alias to a function `os.path.join`, it is not a module
