### ISSUE TITLE
Aggregating multiple runs 

### ISSUE THREAD

**Issue by Amandaobrien8** [PyMVPA/PyMVPA#622]
Hi everyone,

I am using the BIDS PyMVPA app on an fMRI dataset containing three runs. There are multiple conditions within each run. I would like to aggregate the three runs and classify conditions across the runs. What is the best way to aggregate these runs and deal with the new time points? 

Additionally, is there a minimum number of acceptable trials for classification?

Thank you,
Amanda

**Comment by yarikoptic** [comment]
you could `vstack` them I guess and decide on what your new "chunk" (how would you cross-validate) would be etc.   Or just do what you do and assign another chunk to not correspond to run. But since you are asking about BIDS PyMVPA -- ask at https://github.com/BIDS-Apps/PyMVPA since it is not developed by us.
